# Generated by Django 4.2.7 on 2023-12-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_id",
                    models.BigIntegerField(
                        db_comment="Employee ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        db_comment="First Name of employee", max_length=30
                    ),
                ),
                (
                    "lname",
                    models.CharField(db_comment="Last Name of employee", max_length=30),
                ),
                ("email", models.CharField(db_comment="email", max_length=25)),
                ("phone", models.CharField(db_comment="phone number", max_length=10)),
                (
                    "emp_role",
                    models.CharField(
                        blank=True,
                        db_comment="role of employee",
                        max_length=25,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "employee",
                "managed": False,
            },
        ),
    ]
