# Generated by Django 4.2.7 on 2023-12-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "office_id",
                    models.BigIntegerField(
                        db_comment="Rental Office ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "address_houseno",
                    models.BigIntegerField(db_comment="Number of house in address"),
                ),
                (
                    "address_street",
                    models.CharField(
                        db_comment="Street name of address", max_length=30
                    ),
                ),
                (
                    "address_state",
                    models.CharField(
                        db_comment="State of the address abbreviated", max_length=2
                    ),
                ),
                (
                    "address_city",
                    models.CharField(db_comment="City of address", max_length=30),
                ),
                (
                    "address_zipcode",
                    models.CharField(db_comment="Zipcode of address", max_length=5),
                ),
                (
                    "phone",
                    models.CharField(db_comment="Phone of office", max_length=10),
                ),
            ],
            options={
                "db_table": "office",
                "db_table_comment": "Rental offices",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vclass",
            fields=[
                (
                    "classid",
                    models.BigIntegerField(
                        db_comment="Vehicle Class ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "class_name",
                    models.CharField(db_comment="Vehicle class name", max_length=30),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        db_comment="Daily rate of vehicle class",
                        decimal_places=2,
                        max_digits=7,
                    ),
                ),
                (
                    "daily_mileage",
                    models.BigIntegerField(db_comment="Daily mileage of vehicle class"),
                ),
                (
                    "overage_rate",
                    models.DecimalField(
                        db_comment="Overage rate for vehicle class",
                        decimal_places=2,
                        max_digits=7,
                    ),
                ),
            ],
            options={
                "db_table": "vclass",
                "db_table_comment": "Vehicle classes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "vehicle_id",
                    models.BigIntegerField(
                        db_comment="ID Number of Vehicle",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        db_comment="Vehicle Identification Number", max_length=30
                    ),
                ),
                ("make", models.CharField(db_comment="Make of vehicle", max_length=30)),
                (
                    "model",
                    models.CharField(db_comment="Model of vehicle", max_length=30),
                ),
                ("year", models.BigIntegerField(db_comment="Year of the car")),
                (
                    "lp_state",
                    models.CharField(
                        db_comment="License Plate State (abbreviated)", max_length=2
                    ),
                ),
                (
                    "lp_number",
                    models.CharField(db_comment="License Plate number", max_length=8),
                ),
            ],
            options={
                "db_table": "vehicle",
                "db_table_comment": "Vehicles",
                "managed": False,
            },
        ),
    ]
