# Generated by Django 4.2.8 on 2023-12-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wow", "0002_invoice_payment_indivdiscount_corpdiscount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpdiscount",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wow.corpcust",
            ),
        ),
        migrations.AlterField(
            model_name="indivdiscount",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wow.indivcust",
            ),
        ),
    ]
