# Generated by Django 4.2.8 on 2023-12-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wow", "0003_alter_corpdiscount_customer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle", old_name="office_id", new_name="office",
        ),
        migrations.RenameField(
            model_name="vehicle", old_name="class_id", new_name="vclass",
        ),
    ]
