# Generated by Django 5.0 on 2023-12-06 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wow", "0003_customer_rentalservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpCust",
            fields=[
                (
                    "cust",
                    models.OneToOneField(
                        db_comment="Customer ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="wow.customer",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(db_comment="Name of the company", max_length=30),
                ),
                (
                    "company_no",
                    models.CharField(
                        db_comment="Registration number of company", max_length=30
                    ),
                ),
                ("emp_id", models.BigIntegerField(db_comment="ID of the employee")),
            ],
            options={
                "db_table": "corp_cust",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "discid",
                    models.BigIntegerField(
                        db_comment="Discount Coupon ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        db_comment="Percentage of discount in decimals",
                        decimal_places=2,
                        max_digits=7,
                    ),
                ),
                (
                    "disc_type",
                    models.CharField(
                        blank=True,
                        db_comment="Type of Discount",
                        max_length=8,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "discount",
                "db_table_comment": "Discount coupons",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IndivCust",
            fields=[
                (
                    "cust",
                    models.OneToOneField(
                        db_comment="Customer ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="wow.customer",
                    ),
                ),
                (
                    "fname",
                    models.CharField(
                        db_comment="First Name of individual customer", max_length=30
                    ),
                ),
                (
                    "lname",
                    models.CharField(
                        db_comment="Last Name of Individual Customer", max_length=30
                    ),
                ),
                (
                    "licenseno",
                    models.CharField(
                        db_comment="Licence Number of Individual customer",
                        max_length=15,
                    ),
                ),
                (
                    "insurance_co",
                    models.CharField(
                        db_comment="Insurance company name", max_length=30
                    ),
                ),
                (
                    "insurancep_no",
                    models.CharField(
                        db_comment="Insurance policy number", max_length=30
                    ),
                ),
            ],
            options={
                "db_table": "indiv_cust",
                "managed": False,
            },
        ),
    ]
