# Generated by Django 4.2.8 on 2023-12-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wow", "0004_corpcust_discount_indivcust"),
    ]

    operations = [
        migrations.AlterModelOptions(name="corpcust", options={"managed": True},),
        migrations.AlterModelOptions(name="customer", options={"managed": True},),
        migrations.AlterModelOptions(name="discount", options={"managed": True},),
        migrations.AlterModelOptions(name="employee", options={"managed": True},),
        migrations.AlterModelOptions(name="indivcust", options={"managed": True},),
        migrations.AlterModelOptions(name="office", options={"managed": True},),
        migrations.AlterModelOptions(name="rentalservice", options={"managed": True},),
        migrations.AlterModelOptions(name="vclass", options={"managed": True},),
        migrations.AlterModelOptions(name="vehicle", options={"managed": True},),
    ]
