# Generated by Django 4.2.8 on 2023-12-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wow", "0004_rename_office_id_vehicle_office_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceIndivDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wow.indivdiscount",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wow.invoice"
                    ),
                ),
            ],
            options={"unique_together": {("invoice", "discount")},},
        ),
        migrations.CreateModel(
            name="InvoiceCorpDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wow.corpdiscount",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wow.invoice"
                    ),
                ),
            ],
            options={"unique_together": {("invoice", "discount")},},
        ),
    ]
