# Generated by Django 4.2.8 on 2023-12-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wow", "0005_invoiceindivdiscount_invoicecorpdiscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalservice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="rentalservice",
            name="end_odometer",
            field=models.IntegerField(null=True, verbose_name="End Odometer Reading"),
        ),
    ]
