SELECT
    'corp_cust' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'corp_cust' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'corp_cust' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'corp_cust'
UNION
SELECT
    'customer' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'customer' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'customer' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'customer'
UNION
SELECT
    'discount' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'discount' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'discount' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'discount'
UNION
SELECT
    'discount' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'discount' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'discount' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'discount'
UNION
SELECT
    'indiv_cust' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'indiv_cust' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'indiv_cust' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'indiv_cust'
UNION
SELECT
    'individual_disc' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'individual_disc' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'individual_disc' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'individual_disc'
UNION
SELECT
    'inv_disc' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'inv_disc' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'inv_disc' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'inv_disc'
UNION
SELECT
    'invoice' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'invoice' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'invoice' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'invoice'
UNION
SELECT
    'office' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'office' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'office' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'office'
UNION
SELECT
    'payment' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'payment' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'payment' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'payment'
UNION
SELECT
    'rental_service' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'rental_service' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'rental_service' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'rental_service'
UNION
SELECT
    'vclass' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'vclass' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'vclass' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'vclass'
UNION
SELECT
    'vehicle' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_COMMENT,
    CASE
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'vehicle' AND CONSTRAINT_NAME = 'PRIMARY') THEN 'PRIMARY KEY'
        WHEN COLUMN_NAME IN (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'vehicle' AND CONSTRAINT_NAME LIKE 'FK%') THEN 'FOREIGN KEY'
        ELSE NULL
    END AS CONSTRAINT_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'final_wow'
  AND TABLE_NAME = 'vehicle'
;
